name: Laravel CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/id_ed25519
${{ secrets.SSH_KEY }}
EOF
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 7822 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -p 7822 -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_ed25519 \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

            set -e
            cd /home/aminssrj/savings.aminps.org

            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan optimize:clear
            php artisan migrate --force
            php artisan optimize

          EOF
